# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e35f85564f2db8458b947f0a8bc98a8e870c9c9a3042d0c54c083fbf1a3d5e68679cc4122a3bd97bb1aee75e52a5b110cc8aed2cac28dd44935d397391f2ce6

test:
  secret_key_base: 1ea087a86c3d4409cb90ed0d38c52d27eff7d30c8ad89f4cde65d961ff8371616d1b3d04421a37cd0dcf355a559657d068949c5edfe0ef953eefffa71af52995

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
